// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2gN7Tw2YM36TqBcKGYVpG31_hlKa5Kyw',
    appId: '1:730099889115:web:6febdde1d885eb4078adfe',
    messagingSenderId: '730099889115',
    projectId: 'ready-cart-4fc41',
    authDomain: 'ready-cart-4fc41.firebaseapp.com',
    storageBucket: 'ready-cart-4fc41.firebasestorage.app',
    measurementId: 'G-LPSYQJC621',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrWQDv03W1anTtGjH1HHhyEgZFTtN4zpc',
    appId: '1:730099889115:android:0f1b0feec9e932f778adfe',
    messagingSenderId: '730099889115',
    projectId: 'ready-cart-4fc41',
    storageBucket: 'ready-cart-4fc41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZrB7sgbDYf7Gs9btOQYjsK9kRcwanvv4',
    appId: '1:730099889115:ios:041a502481c6250178adfe',
    messagingSenderId: '730099889115',
    projectId: 'ready-cart-4fc41',
    storageBucket: 'ready-cart-4fc41.firebasestorage.app',
    iosBundleId: 'com.example.readyCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZrB7sgbDYf7Gs9btOQYjsK9kRcwanvv4',
    appId: '1:730099889115:ios:041a502481c6250178adfe',
    messagingSenderId: '730099889115',
    projectId: 'ready-cart-4fc41',
    storageBucket: 'ready-cart-4fc41.firebasestorage.app',
    iosBundleId: 'com.example.readyCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2gN7Tw2YM36TqBcKGYVpG31_hlKa5Kyw',
    appId: '1:730099889115:web:de14194768d7df5878adfe',
    messagingSenderId: '730099889115',
    projectId: 'ready-cart-4fc41',
    authDomain: 'ready-cart-4fc41.firebaseapp.com',
    storageBucket: 'ready-cart-4fc41.firebasestorage.app',
    measurementId: 'G-4MBWSYHY62',
  );
}
